import { DefaultTheme } from "react-native-paper";
import { getStatusBarHeight } from "react-native-status-bar-height";
export const theme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    text: "#000000",
    // primary: "#fbcb14",
    primary: "#04acf3",
    secondary: "#414757",
    error: "#f13a59",
  },
  container: {
    flex: 1,
    width: "100%",
  },
  headerContainer: {
    position: "absolute",
    top: getStatusBarHeight(),
    right: 10,
    zIndex: 10,
  },
  separator: {
    marginBottom: 8,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    overflow: "hidden",
    borderBottomColor: "rgba(109, 102, 102, 0.25)",
    borderBottomWidth: 4,
  },
  titleContainer: {
    flex: 1,
    padding: 10,
    marginBottom: 5,
    flexDirection: "row",
    width: "100%",
    height: 82,
    backgroundColor: "#FEFFFF",
    borderColor: "#04ACF3",
    borderWidth: 1,
    borderStyle: "solid",
    borderRadius: 20,
  },
  title: {
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: 24,
    lineHeight: 25,
    width: 212,
    height: 81,
  },
  titleSubContainer: {
    flex: 1,
    flexDirection: "column",
    alignItems: "flex-end",
    width: "100%",
  },
  subTitlePrice: {
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: "bold",
    color: "#04ACF3",
    fontSize: 24,
    lineHeight: 28,
  },
  subTitleInfo: {
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: "bold",
    color: "#615B5B",
    fontSize: 13,
    lineHeight: 15,
    paddingHorizontal: 5,
    width: "100%",
  },
  footer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    width: "100%",
    backgroundColor: "transparent",
  },
};
